server:
  port: 8095
  address: 0.0.0.0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-attestation:3306/attestationDB}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  application:
    name: attestation-service
  main:
    web-application-type: servlet

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

